object_detection:
  ros__parameters:
    input_img_topic: /kitti/camera/color/left/image_raw
    output_bb_topic: object_detection/img_bb
    output_img_topic: object_detection/img
    publish_output_img: 1
    model_params:
      detector_type: YOLOv8
      model_dir_path: /home/mediapipe/Desktop/ros_workspaces/percep_ws/models/yolov8
      weight_file_name: yolov8s.pt
      confidence_threshold : 0.5
      show_fps : 1